app/routes.py
from flask import render_template, redirect, url_for, flash, request
from app import db
from app.forms import RegistrationForm, LoginForm, ContenidoForm, ExamenForm
from app.models import User, Curso, Contenido, Examen, Nota
from flask_login import login_user, current_user, logout_user, login_required
from flask import Blueprint

main = Blueprint('main', __name__)

@main.route("/")
def home():
    if current_user.is_authenticated:
        cursos = Curso.query.filter(
            (Curso.creador.has(id=current_user.id)) | 
            (Curso.usuarios.any(User.id == current_user.id))
        ).all()
    else:
        cursos = []

    return render_template("home.html", cursos=cursos)

@main.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data) 
        db.session.add(user)
        db.session.commit()
        flash('¡Tu cuenta ha sido creada!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Registro', form=form)

@main.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('¡Inicio de sesión exitoso!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Inicio de sesión fallido. Revisa tus credenciales', 'danger')
    return render_template('login.html', title='Login', form=form)

@main.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@main.route('/crear_cursos', methods=['GET', 'POST'])
@login_required
def crear_cursos():
    if request.method == 'POST':
        curso_nombre = request.form.get('curso_nombre')
        curso_descripcion = request.form.get('curso_descripcion')

        if not curso_nombre or not curso_descripcion:
            flash('Todos los campos son obligatorios', 'error')
            return redirect(url_for('main.crear_cursos'))

        nuevo_curso = Curso(nombre=curso_nombre, descripcion=curso_descripcion, user_id=current_user.id)
        
        db.session.add(nuevo_curso)
        db.session.commit()

        flash('Curso creado exitosamente', 'success')
        return redirect(url_for('main.home'))

    return render_template('cursos.html')

@main.route('/eliminar_curso/<int:curso_id>', methods=['POST'])
@login_required
def eliminar_curso(curso_id):
    curso = Curso.query.get_or_404(curso_id)
    if curso.user_id != current_user.id:
        flash('No tienes permiso para eliminar este curso', 'danger')
        return redirect(url_for('main.home'))
    
    db.session.delete(curso)
    db.session.commit()
    flash('Curso eliminado exitosamente', 'success')
    return redirect(url_for('main.home'))

@main.route('/actualizar_curso/<int:curso_id>', methods=['GET', 'POST'])
@login_required  
def actualizar_curso(curso_id):
    curso = Curso.query.get_or_404(curso_id) 

    if request.method == 'POST':
        curso.nombre = request.form.get('curso_nombre')
        curso.descripcion = request.form.get('curso_descripcion')

        if not curso.nombre or not curso.descripcion:
            flash('Todos los campos son obligatorios', 'error')
            return redirect(url_for('main.actualizar_curso', curso_id=curso_id))

        db.session.commit() 
        flash('Curso actualizado exitosamente', 'success')
        return redirect(url_for('main.home'))

    return render_template('actualizar_curso.html', curso=curso)

@main.route('/asignar_estudiante/<int:curso_id>', methods=['GET', 'POST'])
@login_required
def asignar_estudiante(curso_id):
    curso = Curso.query.get_or_404(curso_id)

    if request.method == 'POST':
        email_estudiante = request.form.get('email_estudiante')
        usuario = User.query.filter_by(email=email_estudiante).first()

        if usuario:
            if usuario not in curso.usuarios:
                curso.usuarios.append(usuario)
                db.session.commit()
                flash('Estudiante asignado exitosamente', 'success')
                return redirect(url_for('main.home'))
            else:
                flash('El usuario ya está asignado a este curso.', 'warning')
        else:
            flash('Usuario no encontrado', 'danger')

        return redirect(url_for('main.asignar_estudiante', curso_id=curso_id))

    return render_template('asignar_estudiante.html', curso=curso)

@main.route("/profile/<username>")
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('profile.html', user=user)

@main.route('/curso/<int:curso_id>', methods=['GET'])
@login_required
def curso(curso_id):
    curso = Curso.query.get_or_404(curso_id)

    if current_user not in curso.usuarios and current_user.id != curso.user_id:
        flash('No tienes acceso a este curso', 'danger')
        return redirect(url_for('main.home'))

    examenes = Examen.query.filter_by(curso_id=curso.id).all()

    return render_template('curso.html', curso=curso, examenes=examenes)

@main.route('/agregar_contenido/<int:curso_id>', methods=['GET', 'POST'])
@login_required
def agregar_contenido(curso_id):
    form = ContenidoForm()
    curso = Curso.query.get_or_404(curso_id)

    if form.validate_on_submit():
        nuevo_contenido = Contenido(titulo=form.titulo.data, texto=form.texto.data, curso_id=curso.id)
        db.session.add(nuevo_contenido)
        db.session.commit()
        flash('Contenido agregado exitosamente', 'success')
        return redirect(url_for('main.home'))

    return render_template('agregar_contenido.html', form=form, curso=curso)

@main.route('/agregar_examen/<int:curso_id>', methods=['GET', 'POST'])
@login_required
def agregar_examen(curso_id):
    curso = Curso.query.get_or_404(curso_id)
    form = ExamenForm()

    if form.validate_on_submit():
        nuevo_examen = Examen(titulo=form.titulo.data, contenido=form.contenido.data, curso_id=curso.id)
        db.session.add(nuevo_examen)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('agregar_examen.html', form=form, curso=curso)

@main.route('/asignar_notas/<int:curso_id>', methods=['GET', 'POST'])
@login_required
def asignar_notas(curso_id):
    curso = Curso.query.get_or_404(curso_id)

    if current_user.id != curso.user_id:
        flash('No tienes permiso para asignar notas en este curso.', 'error')
        return redirect(url_for('main.curso', curso_id=curso.id))

    estudiantes = curso.usuarios
    for estudiante in estudiantes:
        estudiante.notas = Nota.query.filter_by(estudiante_id=estudiante.id, curso_id=curso.id).all()

    if request.method == 'POST':
        for key in request.form:
            if key.startswith("nota_"):
                est_id = key.split("_")[1]
                nota_valor = request.form[key]
                nota_registro = Nota.query.filter_by(estudiante_id=est_id, curso_id=curso.id).first()
                if nota_registro:
                    nota_registro.valor = nota_valor
                else:
                    nueva_nota = Nota(estudiante_id=est_id, curso_id=curso.id, valor=nota_valor)
                    db.session.add(nueva_nota)

        db.session.commit()
        flash('Notas asignadas exitosamente', 'success')
        return redirect(url_for('main.curso', curso_id=curso.id))

    return render_template('asignar_notas.html', curso=curso, estudiantes=estudiantes)

@main.route('/eliminar_examen/<int:curso_id>/<int:examen_id>', methods=['POST'])
@login_required
def eliminar_examen(curso_id, examen_id):
    curso = Curso.query.get_or_404(curso_id)
    examen = Examen.query.get_or_404(examen_id)

    if current_user.id != curso.user_id:
        flash('No tienes permiso para eliminar este examen.', 'danger')
        return redirect(url_for('main.curso', curso_id=curso.id))

    db.session.delete(examen)
    db.session.commit()
    flash('Examen eliminado exitosamente', 'success')
    return redirect(url_for('main.curso', curso_id=curso.id))

app/templates/actualizar_curso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Curso</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %} 
    
    <div class="container mt-5">
        <h1>Actualizar Curso</h1>

        <form method="POST" action="{{ url_for('main.actualizar_curso', curso_id=curso.id) }}">
            <div class="mb-3">
                <label for="cursoNombre" class="form-label">Nombre del Curso</label>
                <input type="text" class="form-control" id="cursoNombre" name="curso_nombre" value="{{ curso.nombre }}" required>
            </div>
            <div class="mb-3">
                <label for="cursoDescripcion" class="form-label">Descripción del Curso</label>
                <textarea class="form-control" id="cursoDescripcion" name="curso_descripcion" rows="4" required>{{ curso.descripcion }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar Curso</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/agregar_contenido.html
<h1>Agregar Contenido a {{ curso.nombre }}</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <p>
        {{ form.titulo.label }}<br>
        {{ form.titulo(size=32) }}<br>
        {% for error in form.titulo.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.texto.label }}<br>
        {{ form.texto(rows=5) }}<br>
        {% for error in form.texto.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit() }}</p>
</form>

app/templates/agregar_examen.html
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <div>
        {{ form.titulo.label }} {{ form.titulo(size=32) }}
        {% for error in form.titulo.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.contenido.label }} {{ form.contenido(rows=5) }}
        {% for error in form.contenido.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>

app/templates/asignar_estudiante.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asignar Estudiante</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container mt-5">
        <h1>Asignar Estudiante al Curso: {{ curso.nombre }}</h1>

        <form method="POST">
            <div class="mb-3">
                <label for="email_estudiante" class="form-label">Email del Estudiante</label>
                <input type="email" class="form-control" id="email_estudiante" name="email_estudiante" required>
            </div>
            <button type="submit" class="btn btn-primary">Asignar Estudiante</button>
        </form>
        

        <a href="{{ url_for('main.home') }}" class="btn btn-secondary mt-3">Volver</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app/templates/asignar_notas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asignar Notas - {{ curso.nombre }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

{% include 'navbar.html' %}

<div class="container mt-5">
    <h1>Asignar Notas para {{ curso.nombre }}</h1>

    <form method="POST">
        <table class="table">
            <thead>
                <tr>
                    <th>Estudiante</th>
                    <th>Nota</th>
                </tr>
            </thead>
            <tbody>
                {% for estudiante in estudiantes %}
                <tr>
                    <td>{{ estudiante.username }}</td>
                    <td>
                        {% set nota = estudiante.notas | first %}
                        <input type="number" name="nota_{{ estudiante.id }}" value="{{ nota.valor if nota else '' }}" class="form-control" required>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="2">No hay estudiantes inscritos en este curso.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">Asignar Notas</button>
    </form>
</div>

</body>
</html>

app/templates/curso.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ curso.nombre }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            background-color: #f8f9fa;
            color: #343a40;
        }

        h1,
        h2 {
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .content-section {
            padding: 20px;
            background: #ffffff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-danger {
            background-color: #dc3545;
            border-color: #dc3545;
        }

        .btn-secondary {
            background-color: #6c757d;
            border-color: #6c757d;
        }
    </style>
</head>

<body>

    {% include 'navbar.html' %}

    <div class="container">
        <h1>{{ curso.nombre }}</h1>
        <p>{{ curso.descripcion }}</p>

        <div class="content-section">
            <h2>Contenido</h2>
            {% for contenido in curso.contenidos %}
            <h3>{{ contenido.titulo }}</h3>
            <p>{{ contenido.texto }}</p>
            {% endfor %}

            {% if current_user.id == curso.user_id %}
            <a href="{{ url_for('main.agregar_contenido', curso_id=curso.id) }}" class="btn btn-primary">Agregar
                Contenido</a>
            {% endif %}
        </div>

        <div class="content-section">
            <h2>Exámenes</h2>
            {% for examen in examenes %}
            <div class="d-flex align-items-center mb-2">
                <div class="me-auto">
                    <p>{{ examen.titulo }}</p>
                    <p>
                        {% for estudiante in curso.usuarios %}
                        {% set nota = estudiante.notas | first %}
                        <strong>{{ estudiante.username }}: {{ nota.valor if nota else 'Sin nota' }}</strong>
                        {% endfor %}
                    </p>
                </div>
                {% if current_user.id == curso.user_id %}
                <div class="ms-2">
                    <a href="{{ url_for('main.asignar_notas', curso_id=curso.id) }}" class="btn btn-secondary">Asignar
                        Nota</a>
                </div>
                <div class="ms-2">
                    <form action="{{ url_for('main.eliminar_examen', examen_id=examen.id, curso_id=curso.id) }}"
                        method="POST" style="display:inline;">
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
                {% endif %}

            </div>
            {% endfor %}
        </div>

        {% if current_user.id == curso.user_id %}
        <div class="mt-4">
            <a href="{{ url_for('main.agregar_examen', curso_id=curso.id) }}" class="btn btn-primary">Agregar examen</a>
        </div>
        {% endif %}
    </div>

</body>

</html>

app/templates/cursos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Cursos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='cursos.css') }}">
</head>
<body>
    {% include 'navbar.html' %}
    
    <div class="container mt-5">
        <h1 class="mb-4">Crear Curso</h1>
        <form method="POST" action="{{ url_for('main.crear_cursos') }}">
            <div class="mb-3">
                <label for="cursoNombre" class="form-label">Nombre del Curso</label>
                <input type="text" class="form-control" id="cursoNombre" name="curso_nombre" required>
            </div>
            <div class="mb-3">
                <label for="cursoDescripcion" class="form-label">Descripción del Curso</label>
                <textarea class="form-control" id="cursoDescripcion" name="curso_descripcion" rows="4" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Crear Curso</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
</head>

<body>
    {% include 'navbar.html' %}

    <div class="container mt-5">
        <h1>Aula.</h1>

        <h2 class="mt-4">Todos los Cursos</h2>
        <table class="table table-bordered mt-3">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Profesor</th>
                    <th>Estudiantes Asignados</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for curso in cursos %}
                <tr>
                    <td>{{ curso.nombre }}</td>
                    <td>{{ curso.descripcion }}</td>
                    <td>{{ curso.creador.username }}</td>
                    <td>
                        {% if curso.usuarios %}  
                            <ul>
                                {% for usuario in curso.usuarios %}  
                                    <li>{{ usuario.username }} ({{ usuario.email }})</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            No hay estudiantes asignados.
                        {% endif %}
                    </td>
                    <td>
                        {% if current_user.id == curso.user_id %} 
                            <form action="{{ url_for('main.eliminar_curso', curso_id=curso.id) }}" method="POST"
                                style="display:inline;">
                                <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                            </form>
                            <a href="{{ url_for('main.actualizar_curso', curso_id=curso.id) }}"
                                class="btn btn-warning btn-sm">Actualizar</a>
                        
                            <a href="{{ url_for('main.asignar_estudiante', curso_id=curso.id) }}"
                                class="btn btn-primary btn-sm">Asignar Estudiante</a>
                        {% endif %}
            
                        <a href="{{ url_for('main.curso', curso_id=curso.id) }}" 
                            class="btn btn-primary btn-sm">Entrar al curso</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% if not cursos %}
        <p>No hay cursos disponibles.</p>
        {% endif %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <form method="POST" action="{{ url_for('main.login') }}">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }}
        </div>
        <div class="text-center">
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </div>
    </form> 

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.crear_cursos') }}">Crear Cursos</a>
                </li>
            </ul>
            <div class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('main.profile', username=current_user.username) }}" class="btn btn-outline-info me-2">
                        {{ current_user.username }}
                    </a>
                    <a href="{{ url_for('main.logout') }}" class="btn btn-outline-danger">Cerrar Sesión</a>
                {% else %}
                    <a href="{{ url_for('main.login') }}" class="btn btn-outline-primary me-2">Iniciar Sesión</a>
                    <a href="{{ url_for('main.register') }}" class="btn btn-outline-secondary">Registrarse</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<style>
    .navbar {
        padding: 1rem 1rem;
    }

    .nav-link {
        transition: color 0.3s;
    }

    .nav-link:hover {
        color: #f8f9fa;
        text-decoration: underline;
    }

    .btn-outline-info, .btn-outline-primary, .btn-outline-secondary {
        transition: background-color 0.3s, border-color 0.3s;
    }

    .btn-outline-info:hover {
        background-color: #17a2b8;
        border-color: #17a2b8;
    }

    .btn-outline-primary:hover {
        background-color: #007bff;
        border-color: #007bff;
    }

    .btn-outline-secondary:hover {
        background-color: #6c757d;
        border-color: #6c757d;
    }
</style>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Cursos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='cursos.css') }}">
</head>
<body>

    {% include 'navbar.html' %}

    {% block content %}
    <div class="container mt-4">
        <h1>Perfil de {{ user.username }}</h1>
        <ul class="list-group">
            <li class="list-group-item">Correo: {{ user.email }}</li>
            <li class="list-group-item">Usuario: {{ user.username }}</li>
        </ul>
    </div>
    {% endblock %}

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <form method="POST" action="{{ url_for('main.register') }}">
        {{ form.hidden_tag() }}

        <div class="form-group">
            {{ form.username.label(class="form-label") }}
            {{ form.username(class="form-control", id="exampleInputUsername", placeholder="Enter username") }}
        </div>

        <div class="form-group">
            {{ form.email.label(class="form-label") }}
            {{ form.email(class="form-control", id="exampleInputEmail1", **{'aria-describedby': 'emailHelp', 'placeholder': 'Enter email'}) }}
        </div>

        <div class="form-group">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control", id="exampleInputPassword1", placeholder="Password") }}
        </div>

        <div class="text-center">
            {{ form.submit(class="btn btn-primary", id="submitBtn") }}
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>